export const mockSetups = [
  {
    id: "rec_acme_prorunner",
    Client: "Acme Sports",
    "Product Name": "ProRunner X1",
    Keyword: "buy acme prorunner replica",
  },
  {
    id: "rec_acme_trail",
    Client: "Acme Sports",
    "Product Name": "TrailBlaze 500",
    Keyword: "acme trailblaze fake cheap",
  },
  {
    id: "rec_lux_tote",
    Client: "LuxBrand",
    "Product Name": "Classic Tote",
    Keyword: "lux brand fake bag cheap",
  },
  {
    id: "rec_lux_wallet",
    Client: "LuxBrand",
    "Product Name": "Signature Wallet",
    Keyword: "luxbrand wallet replica buy online",
  },
  {
    id: "rec_lux_belt",
    Client: "LuxBrand",
    "Product Name": "Signature Wallet",
    Keyword: "luxbrand belt knockoff",
  },
];

export const mockSightings: Record<string, any[]> = {
  rec_acme_prorunner: [
    {
      id: "sight_001",
      URL: "https://replica-sneakers.example/acme-prorunner-x1-copy/",
      Status: "Takedown Recommended",
      "Risk Score": 0.94,
      "Confidence Score": 0.91,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        "Website explicitly markets itself as selling 1:1 copies of the Acme ProRunner X1 at a fraction of the retail price. Product images appear to be taken directly from the official Acme catalog. Clear counterfeit operation.",
      Client: "Acme Sports",
      "Product Name": "ProRunner X1",
      Keyword: "buy acme prorunner replica",
    },
    {
      id: "sight_002",
      URL: "https://cheapkicks.example/acme-inspired-running-shoe/",
      Status: "Takedown Recommended",
      "Risk Score": 0.81,
      "Confidence Score": 0.85,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        'Page sells "Acme-inspired" shoes using registered Acme trademarks prominently in product titles and meta tags. Pricing ($28) far below genuine retail ($189) strongly suggests counterfeit goods.',
      Client: "Acme Sports",
      "Product Name": "ProRunner X1",
      Keyword: "buy acme prorunner replica",
    },
    {
      id: "sight_003",
      URL: "https://runnersblog.example/acme-prorunner-x1-review-2024/",
      Status: "Auto Closed",
      "Risk Score": 0.08,
      "Confidence Score": 0.93,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Editorial review blog comparing genuine Acme ProRunner X1 against competitors. No counterfeit products sold. Links to official retailers only. No IP infringement detected.",
      Client: "Acme Sports",
      "Product Name": "ProRunner X1",
      Keyword: "buy acme prorunner replica",
    },
    {
      id: "sight_004",
      URL: "https://alimarket.example/item/88234771/",
      Status: "Takedown Recommended",
      "Risk Score": 0.88,
      "Confidence Score": 0.79,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        "Marketplace listing uses official Acme product photography and logo. Seller ships from undisclosed location, no authorized reseller status. High likelihood of counterfeit product.",
      Client: "Acme Sports",
      "Product Name": "ProRunner X1",
      Keyword: "buy acme prorunner replica",
    },
    {
      id: "sight_005",
      URL: "https://greymarket-sports.example/acme-prorunner-x1-eu/",
      Status: "analyzed",
      "Risk Score": 0.47,
      "Confidence Score": 0.68,
      "Infringement Type": "grey_market",
      "Recommended Action": "human_review",
      "Reasoning Summary":
        "Reseller offering genuine Acme products imported outside authorized distribution channels. Products appear authentic but sold below MAP. Grey market activity — not counterfeit but potentially in violation of distribution agreements.",
      Client: "Acme Sports",
      "Product Name": "ProRunner X1",
      Keyword: "buy acme prorunner replica",
    },
  ],

  rec_acme_trail: [
    {
      id: "sight_006",
      URL: "https://faketrailgear.example/acme-trailblaze-500-clone/",
      Status: "Takedown Recommended",
      "Risk Score": 0.96,
      "Confidence Score": 0.94,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        'Site openly advertises "TrailBlaze 500 clones" with registered Acme branding. Product descriptions and images are copied verbatim from acmesports.com. Clear trademark and copyright infringement.',
      Client: "Acme Sports",
      "Product Name": "TrailBlaze 500",
      Keyword: "acme trailblaze fake cheap",
    },
    {
      id: "sight_007",
      URL: "https://outdoorforum.example/threads/trailblaze-500-alternatives/",
      Status: "Auto Closed",
      "Risk Score": 0.12,
      "Confidence Score": 0.88,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Forum thread discussing budget alternatives to the TrailBlaze 500. No counterfeit products mentioned or sold. Community discussion only.",
      Client: "Acme Sports",
      "Product Name": "TrailBlaze 500",
      Keyword: "acme trailblaze fake cheap",
    },
    {
      id: "sight_008",
      URL: "https://discountsports.example/acme-trailblaze/",
      Status: "analyzed",
      "Risk Score": 0.35,
      "Confidence Score": 0.72,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Authorized discount retailer selling genuine TrailBlaze 500 units from last season at reduced prices. Reseller agreement on file. No infringement.",
      Client: "Acme Sports",
      "Product Name": "TrailBlaze 500",
      Keyword: "acme trailblaze fake cheap",
    },
  ],

  rec_lux_tote: [
    {
      id: "sight_009",
      URL: "https://handbag-replicas.example/luxbrand-classic-tote-aaa/",
      Status: "Takedown Recommended",
      "Risk Score": 0.97,
      "Confidence Score": 0.96,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        'Page sells "AAA quality" LuxBrand Classic Tote replicas with authentic-looking dust bags and authenticity cards. Uses LuxBrand registered logo throughout. High-confidence counterfeit operation targeting luxury consumers.',
      Client: "LuxBrand",
      "Product Name": "Classic Tote",
      Keyword: "lux brand fake bag cheap",
    },
    {
      id: "sight_010",
      URL: "https://fashionblog.example/luxbrand-classic-tote-honest-review/",
      Status: "Auto Closed",
      "Risk Score": 0.06,
      "Confidence Score": 0.97,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Fashion influencer honest review of a genuine LuxBrand Classic Tote purchased through official channels. No counterfeit content, positive brand representation.",
      Client: "LuxBrand",
      "Product Name": "Classic Tote",
      Keyword: "lux brand fake bag cheap",
    },
    {
      id: "sight_011",
      URL: "https://dhmarket.example/product/lux-style-tote-bag-1892/",
      Status: "Takedown Recommended",
      "Risk Score": 0.83,
      "Confidence Score": 0.81,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        'Marketplace listing for a "LUX style tote" using protected trade dress and color combination. Product dimensions, hardware details, and stitching pattern are direct copies of the Classic Tote design.',
      Client: "LuxBrand",
      "Product Name": "Classic Tote",
      Keyword: "lux brand fake bag cheap",
    },
    {
      id: "sight_012",
      URL: "https://preloved-luxury.example/luxbrand-classic-tote-used/",
      Status: "Auto Closed",
      "Risk Score": 0.18,
      "Confidence Score": 0.82,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Pre-owned luxury resale platform listing an authenticated second-hand LuxBrand Classic Tote. Authenticity verification service mentioned. First-sale doctrine applies — no infringement.",
      Client: "LuxBrand",
      "Product Name": "Classic Tote",
      Keyword: "lux brand fake bag cheap",
    },
  ],

  rec_lux_wallet: [
    {
      id: "sight_013",
      URL: "https://replica-wallets.example/luxbrand-signature-wallet-copy/",
      Status: "Takedown Recommended",
      "Risk Score": 0.92,
      "Confidence Score": 0.89,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        "Direct counterfeit of the LuxBrand Signature Wallet sold with forged authenticity certificate. Seller offers multiple color variants matching the current season collection.",
      Client: "LuxBrand",
      "Product Name": "Signature Wallet",
      Keyword: "luxbrand wallet replica buy online",
    },
    {
      id: "sight_014",
      URL: "https://stylecompare.example/luxbrand-wallet-vs-alternatives/",
      Status: "Auto Closed",
      "Risk Score": 0.09,
      "Confidence Score": 0.91,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Price comparison article contrasting the LuxBrand Signature Wallet with affordable legitimate alternatives. No counterfeit products. Educational content only.",
      Client: "LuxBrand",
      "Product Name": "Signature Wallet",
      Keyword: "luxbrand wallet replica buy online",
    },
    {
      id: "sight_015",
      URL: "https://socialshop.example/listing/lb-inspired-wallet-88127/",
      Status: "analyzed",
      "Risk Score": 0.61,
      "Confidence Score": 0.74,
      "Infringement Type": "design_copy",
      "Recommended Action": "human_review",
      "Reasoning Summary":
        '"LB-inspired" wallet copies the distinctive LuxBrand monogram pattern. Does not use the registered trademark directly but trade dress violation is likely. Requires legal review to determine actionability.',
      Client: "LuxBrand",
      "Product Name": "Signature Wallet",
      Keyword: "luxbrand wallet replica buy online",
    },
  ],

  rec_lux_belt: [
    {
      id: "sight_016",
      URL: "https://knockoff-accessories.example/luxbrand-belt-replica-35mm/",
      Status: "Takedown Recommended",
      "Risk Score": 0.89,
      "Confidence Score": 0.87,
      "Infringement Type": "counterfeit",
      "Recommended Action": "escalate",
      "Reasoning Summary":
        "Replica LuxBrand belt with counterfeit buckle logo. Seller ships in packaging using LuxBrand trade dress. Clearly counterfeit product sold at 1/10th of retail price.",
      Client: "LuxBrand",
      "Product Name": "Signature Wallet",
      Keyword: "luxbrand belt knockoff",
    },
    {
      id: "sight_017",
      URL: "https://fashionforum.example/is-this-luxbrand-belt-real/",
      Status: "Auto Closed",
      "Risk Score": 0.14,
      "Confidence Score": 0.9,
      "Infringement Type": "not_infringing",
      "Recommended Action": "auto_close",
      "Reasoning Summary":
        "Forum thread where user asks for authenticity verification of a LuxBrand belt they received as a gift. No counterfeit products sold. Community discussion only.",
      Client: "LuxBrand",
      "Product Name": "Signature Wallet",
      Keyword: "luxbrand belt knockoff",
    },
  ],
};

// In-memory store: maps mock runId → setupRecordId so results can be filtered
export const mockRunStore = new Map<string, string>();
